name: Merge upstream

on:
  schedule:
    - cron:  '* * * * *'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: awesome-selfhosted/awesome-selfhosted
          upstream-branch: master
          branch: master
