name: Merge upstream

on:
  schedule:
    - cron:  '* * * * *'
  workflow_dispatch:

jobs:
  merge_upstream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout target repo
      uses: actions/checkout@v2
      with:
        ref: master
        persist-credentials: false

    - name: Merge upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.1
      with:
        target_sync_branch: master
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: master
        upstream_sync_repo: awesome-selfhosted/awesome-selfhosted
